/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/AV_logo1.glb --transform 
Files: public/models/AV_logo1.glb [58.13KB] > C:\Users\Jerry\Desktop\website2.0\AV_logo1-transformed.glb [7.95KB] (86%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/AV_logo1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.l4c.geometry} material={materials.core} position={[-1.802, 0.283, -0.025]} />
      <mesh geometry={nodes.l1001.geometry} material={materials.shell} position={[-2.431, -0.292, 0.014]} />
    </group>
  )
}

useGLTF.preload('/AV_logo1-transformed.glb')
