/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/partslogo.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/partslogo.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.l4_cell.geometry} material={materials.logo} position={[-1.741, 0.299, -0.026]} />
      <mesh geometry={nodes.l4_cell001.geometry} material={materials.logo} position={[-1.812, 0.324, -0.026]} />
      <mesh geometry={nodes.l4_cell002.geometry} material={materials.logo} position={[-1.79, 0.219, -0.013]} />
      <mesh geometry={nodes.l4_cell003.geometry} material={materials.logo} position={[-1.854, 0.251, -0.019]} />
      <mesh geometry={nodes.l4_cell004.geometry} material={materials.logo} position={[-1.752, 0.297, 0.029]} />
      <mesh geometry={nodes.l4_cell005.geometry} material={materials.logo} position={[-1.813, 0.342, 0.026]} />
      <mesh geometry={nodes.l4_cell006.geometry} material={materials.logo} position={[-1.801, 0.198, 0.028]} />
      <mesh geometry={nodes.l4_cell007.geometry} material={materials.logo} position={[-1.833, 0.267, 0.025]} />
      <mesh geometry={nodes.l3_cell.geometry} material={materials.logo} position={[-1.694, -0.279, -0.006]} />
      <mesh geometry={nodes.l3_cell001.geometry} material={materials.logo} position={[-1.745, -0.271, -0.012]} />
      <mesh geometry={nodes.l3_cell002.geometry} material={materials.logo} position={[-2.031, 0.196, 0]} />
      <mesh geometry={nodes.l3_cell003.geometry} material={materials.logo} position={[-1.918, 0.135, -0.014]} />
      <mesh geometry={nodes.l3_cell004.geometry} material={materials.logo} position={[-1.74, -0.357, 0.04]} />
      <mesh geometry={nodes.l3_cell005.geometry} material={materials.logo} position={[-1.688, -0.312, 0.037]} />
      <mesh geometry={nodes.l3_cell006.geometry} material={materials.logo} position={[-2.098, 0.321, 0.032]} />
      <mesh geometry={nodes.l3_cell007.geometry} material={materials.logo} position={[-2.015, 0.274, 0.004]} />
      <mesh geometry={nodes.l2_cell.geometry} material={materials.logo} position={[-2.073, -0.139, 0.003]} />
      <mesh geometry={nodes.l2_cell001.geometry} material={materials.logo} position={[-2.042, -0.264, -0.002]} />
      <mesh geometry={nodes.l2_cell002.geometry} material={materials.logo} position={[-2.339, 0.317, -0.024]} />
      <mesh geometry={nodes.l2_cell003.geometry} material={materials.logo} position={[-2.149, 0.193, -0.041]} />
      <mesh geometry={nodes.l2_cell004.geometry} material={materials.logo} position={[-2.043, -0.257, 0.033]} />
      <mesh geometry={nodes.l2_cell005.geometry} material={materials.logo} position={[-2.065, -0.097, 0.034]} />
      <mesh geometry={nodes.l2_cell006.geometry} material={materials.logo} position={[-2.334, 0.343, -0.006]} />
      <mesh geometry={nodes.l1_cell.geometry} material={materials.logo} position={[-2.432, -0.327, -0.028]} />
      <mesh geometry={nodes.l1_cell001.geometry} material={materials.logo} position={[-2.356, -0.352, -0.036]} />
      <mesh geometry={nodes.l1_cell002.geometry} material={materials.logo} position={[-2.297, 0.005, -0.024]} />
      <mesh geometry={nodes.l1_cell003.geometry} material={materials.logo} position={[-2.311, -0.108, -0.029]} />
      <mesh geometry={nodes.l1_cell004.geometry} material={materials.logo} position={[-2.446, -0.306, 0.027]} />
      <mesh geometry={nodes.l1_cell005.geometry} material={materials.logo} position={[-2.377, -0.275, -0.011]} />
      <mesh geometry={nodes.l1_cell006.geometry} material={materials.logo} position={[-2.299, -0.027, 0.013]} />
      <mesh geometry={nodes.l1_cell007.geometry} material={materials.logo} position={[-2.312, -0.148, 0.016]} />
      <mesh geometry={nodes.l3_cell008.geometry} material={materials.logo} position={[-1.759, -0.228, 0.015]} />
      <mesh geometry={nodes.l3_cell009.geometry} material={materials.logo} position={[-1.896, -0.011, -0.004]} />
      <mesh geometry={nodes.l2_cell008.geometry} material={materials.logo} position={[-2.162, 0.099, -0.013]} />
      <mesh geometry={nodes.l2_cell009.geometry} material={materials.logo} position={[-2.269, 0.301, -0.008]} />
    </group>
  )
}

useGLTF.preload('/partslogo.glb')
