/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/EXAV.glb --info 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/EXAV.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane003_cell.geometry} material={materials['Material.001']} position={[-2.478, -2.126, -1.592]} />
    </group>
  )
}

useGLTF.preload('/EXAV.glb')
